//1.first/initially make one global variable started  as false
let started=false;
//starting level should be zero
level=0;

//2.select h2 when game started and change the text
let h2=document.querySelector("h2")

//3.make list of colurs and randomly slect one of the colors(i.e randomly select index of the color, use Math.random)
let btns=["red","yellow","purple","green"];

//5. so u want to remeber the blinked colors internally(machine need to remeber, so that u can decide wether the user/player is clicking correct sequence/not)
let gameSeq=[];

//6.maintain user clicked color sequence also
let userSeq=[];

document.addEventListener("keypress",function(event){
    //waiting user to press any key and when user press key some message needs to be displayed 
    //if game already started ,don't do anything, if it is false(i.e game not tarted then only wait for user to press anykey from keyboard)

    if(started===false){
        console.log("Game Started");
        //make started true
        started=true;

        //we will have levelup ftn, when u click any key from keyboard, one among the box should blikn and levels should keep on increasing
        levelUp();

    }
})

//4.function for flashing btn
function btnFlash(btn){
    //change that btn color to white(use classList property and the new class "flash" u defined in css file)
    btn.classList.add("flash");

//the above line of code makes the bg-color white of the random btn permanaetly, so again u want the same color back so add the setTimeout(after sometime(3 seconds) remove the flash class)
    setTimeout(function(){
    btn.classList.remove("flash");
    },3000);
}

function levelUp(){
    userSeq=[];
    console.log("Level Up");
    level++;
    //change text to Level counts(use backticks to add expression in string)
    h2.innerText=`Level ${level}`;

    //generate random nor's from 0 to 3, so use Math.random(generates radoms numbers from 0 to 3, 4 values(0,1,2,3))
    let ranIndx=Math.floor(Math.random()*4);
    let randColor=btns[ranIndx];
    console.log(randColor);

    //now the list of the colrs/btns u gave are same as the class names, use these randcolor generated each time to select the btn respective btn on the page
    let randBtn=document.querySelector(`.${randColor}`);

    //push the blinked colors in the array so they will be in sequence
    gameSeq.push(randColor);
    //4. i will flash that btn 
    btnFlash(randBtn);

}

//5. for...of loop on all btns

//i will collect all btns from btn-container

//when user clicks i want black flash
function userFlash(btn){
    btn.classList.add("userflash");
    setTimeout(function(){
        btn.classList.remove("userflash");
    },300);
}

//7 Reset the game
function resetGame(){
    started=false;
    gameSeq=[];
    userSeq=[];
    level=0;
}
//6. Chechanswerftn
function checAns(){
    //we will take the last index from userseq and gameseq(which is generated randomly)
    let idx=userSeq.length-1;
    //if user pressed color and color generated by system(we will compare the last index see from above line)
    if(userSeq[idx]===gameSeq[idx]){
        console.log("Success");
        //if user press correct number of times(colors) as the system generated times colors if both are equal, then levelup after 1 second
        if(userSeq.length===gameSeq.length){
            setTimeout(levelUp,1000);
        }
    }
    else{
        h2.innerText=`Game Over! score ${level} Press any other key to start.`
        resetGame();
    }
}
function btnPress(){
    userFlash(this);
    useColor=this.getAttribute("id");
    userSeq.push(useColor);

    //check the answer of user sequence correct or not(Check Answer ftn)
    checAns();
}

allbtns=document.querySelectorAll('.btn-container .btn')

for(btn of allbtns){
    btn.addEventListener("click",btnPress);
}


